name: Publish to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[publish]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.25 # https://github.com/oven-sh/bun/issues/8759
      - run: bun install
      - run: bun ci
      - uses: ArnaudBarre/npm-publish@v1
        with:
          working-directory: dist
          npm-token: ${{ secrets.NPM_TOKEN }}
